name: "Autosend"

on:
  push:
    branches: master
  schedule:
    - cron: '30 0 */10 * *' # 每10天0点30分自动执行，UTC时间
  workflow_dispatch:
    inputs: {}

jobs:
  autosend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: pushBotMsg
        uses: joelwmale/webhook-action@master
        with:
          url: "https://api.groupme.com/v3/bots/post"
          body: '{"text" : "keepGV active", "bot_id" : "${{ secrets.GM_BOT_ID }}" }'
